{% set name = "django-data-browser" %}
{% set version = "4.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-data-browser-{{ version }}.tar.gz
  sha256: 578b0550ff40ba9ca66e8d46eec15f53078f95afa17d2c1a8c82b4d80c7e1d9c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - django >=3.2
    - hyperlink
    - python-dateutil
    - sqlparse

test:
  imports:
    - data_browser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tolomea/django-data-browser
  summary: Interactive user-friendly database explorer.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
