{% set name = "django-data-browser" %}
{% set version = "4.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-data-browser-{{ version }}.tar.gz
  sha256: b4ba9b00548d5d8d84edd045bbf8dc7b8d4a56b73e85bc37baf863f7903e4d3c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - django >=3.2
    - hyperlink
    - python-dateutil
    - sqlparse

test:
  imports:
    - data_browser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tolomea/django-data-browser
  summary: Interactive user-friendly database explorer.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
